### PR TITLE
Move package to root

### PR DESCRIPTION
**Pull request by sevein**
I think that the majority of users expect from a Go library to expose its package from the root.

However, I can't get this to compile.
`dyld: Library not loaded: libs/libtgl.so`.

I have no idea of what I'm doing... :)

### CODE REVIEW

**Comment by sevein** [comment]
I can't get this to work,  ```error while loading shared libraries: libtgl.so```. I'll dig into it.

**Comment by gloob** [comment]
You moved so much :-) I prefer that we maintain the lib in ./lib/tgl to have a clear overview that we are using an external dependency directly into the repo. Also we need to update some documentation that is missing.

For next time I would prefer to have separated commits, one for moving, other for the inclusion of new code into tests, etc... Because probably the problem with the library is because we are actually using code.

I will merge it and fix the build, thanks!

**Comment by gloob** [comment]
Good job!, merged into the project.

**Comment by sevein** [comment]
:+1:

**Pull request merged**
